version: '3.3'

services:
  flask-app:
    build:
      context: ./backend
    image: flask-app:latest
    container_name: flask-app
    ports:
      - "5000:5000"

  react-bomb:
    build:
      context: ./my-react-app
    image: react-bomb:latest
    container_name: react-bomb
    ports:
      - "3000:3000"
    depends_on:
      - flask-app
